name: Secure Terraform Pipeline

on:
  push:
    branches:
      - main

jobs:
  security-scan:
    name: üõ°Ô∏è Security Scan (tfsec)
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Guvenlik Taramasi Yap
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          soft_fail: true # Hata bulsa bile durmasin (Ogrenme amacli)

  terraform:
    name: üèóÔ∏è Terraform Apply
    needs: security-scan # Once guvenlik taramasi bitsin
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v3

      - name: Terraform Kurulumu
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1"

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "eu-central-1"